alias: "Front Doorbell: Person Detected"
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.camera1_person
    to:
      - "on"
conditions: []
actions:
  - data:
      data:
        channel: Home camera priority
        priority: high
        ttl: 0
        image: "{{states.camera.camera1_fluent.attributes.entity_picture}}"
        url: /security
      message: Person detected
    action: notify.mobile_app_pixel_8
  - action: media_player.volume_set
    metadata: {}
    target:
      entity_id: media_player.home_assistant_voice_091b0c_media_player
    data:
      volume_level: 1
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - action: script.play_alpha_centauri_sound_on_livingroom
    metadata: {}
    data:
      soundfile: media-source://media_source/local/CPU indigenous lifeforms.wav
mode: single
