alias: "Mower: Notify complete"
description: ""
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.mo99_progress
    above: 99
conditions: []
actions:
  - data:
      title: Mo
      message: Mowing has finished
      data:
        channel: Mo automation
        priority: high
        ttl: 0
        notification_icon: mdi:robot-mower
    action: notify.mobile_app_pixel_8
  - action: input_number.set_value
    metadata: {}
    data:
      value: 0
    target:
      entity_id: input_number.days_since_last_mow
mode: single
