alias: "Mower: Notify complete"
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.mo99_activity_mode
    to: MODE_READY
    enabled: false
    from: MODE_RETURNING
  - trigger: numeric_state
    entity_id:
      - sensor.mo99_progress
    above: 99
conditions: []
actions:
  - data:
      title: Mo
      message: Mowing has finished
      data:
        channel: Mo automation
        priority: high
        ttl: 0
        notification_icon: mdi:robot-mower
    action: notify.mobile_app_pixel_8
mode: single
