alias: "Mower: Notify error"
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.mo99_activity_mode
    from: MODE_WORKING
    to: MODE_PAUSE
conditions: []
actions:
  - data:
      title: Mo
      message: An error has occured, check if Mo is stuck
      data:
        channel: Mo automation
        priority: high
        ttl: 0
        notification_icon: mdi:robot-mower
    action: notify.mobile_app_pixel_8
mode: single
