alias: "Mower: Notify complete"
description: ""
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.mo99_time_left
    below: 5
conditions:
  - condition: lawn_mower.is_mowing
    target:
      device_id: c1a6fce56e3605c6ec1e00d22321e2f2
    options:
      behavior: any
actions:
  - data:
      title: Mo
      message: Mowing has finished
      data:
        channel: Mo automation
        priority: high
        ttl: 0
        notification_icon: mdi:robot-mower
    action: notify.mobile_app_pixel_8
  - action: input_datetime.set_datetime
    metadata: {}
    target:
      entity_id: input_datetime.mower_last_mowed_date
    data:
      date: "{{ now().strftime('%Y-%m-%d') }}"
  - action: script.play_alpha_centauri_sound_on_livingroom
    metadata: {}
    data:
      soundfile: media-source://media_source/local/CPU terraform complete.wav
mode: single
