alias: "Mower: power on for mowing days"
description: ""
triggers:
  - trigger: time
    at: "23:00:00"
conditions:
  - condition: numeric_state
    entity_id: input_number.days_since_last_mow
    above: 1
actions:
  - if:
      - condition: state
        entity_id: switch.mower_outlet
        state: "off"
    then:
      - action: switch.turn_on
        metadata: {}
        data: {}
        target:
          entity_id:
            - switch.mower_outlet
            - switch.mo99_turn_updates_on_off
mode: single
