- id: '1701925904350'
  name: Power off
  entities:
    light.basement_light_1:
      min_color_temp_kelvin: 2700
      max_color_temp_kelvin: 5000
      min_mireds: 200
      max_mireds: 370
      supported_color_modes:
      - brightness
      - color_temp
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      friendly_name: Basement light 1
      supported_features: 32
      state: 'off'
    light.basement_light_2:
      min_color_temp_kelvin: 2700
      max_color_temp_kelvin: 5000
      min_mireds: 200
      max_mireds: 370
      supported_color_modes:
      - brightness
      - color_temp
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      friendly_name: Basement light 2
      supported_features: 32
      state: 'off'
    switch.bedroom:
      friendly_name: Bedroom
      state: 'off'
    light.entryway:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 9000
      min_mireds: 111
      max_mireds: 400
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      friendly_name: Entryway
      supported_features: 32
      state: 'off'
    switch.garage_light:
      friendly_name: Garage light
      state: 'off'
    switch.kitchen_1:
      friendly_name: Kitchen 1
      state: 'off'
    light.living_1:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 9000
      min_mireds: 111
      max_mireds: 400
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      friendly_name: Living 1
      supported_features: 32
      state: 'off'
    light.living_2:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 9000
      min_mireds: 111
      max_mireds: 400
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      friendly_name: Living 2
      supported_features: 32
      state: 'off'
    light.office_1:
      min_color_temp_kelvin: 2700
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 370
      supported_color_modes:
      - brightness
      - color_temp
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      friendly_name: office 1
      supported_features: 32
      state: 'off'
    light.office_2:
      min_color_temp_kelvin: 2700
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 370
      supported_color_modes:
      - brightness
      - color_temp
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      friendly_name: office 2
      supported_features: 32
      state: 'off'
    light.office_backlight:
      min_color_temp_kelvin: 2700
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 370
      supported_color_modes:
      - brightness
      - color_temp
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      friendly_name: Office Backlight
      supported_features: 32
      state: 'off'
    media_player.tv:
      friendly_name: TV
      supported_features: 152461
      state: 'off'
  metadata: {}
- id: '1702911831464'
  name: Indoor Power Off
  entities:
    light.basement_light_1:
      min_color_temp_kelvin: 2700
      max_color_temp_kelvin: 5000
      min_mireds: 200
      max_mireds: 370
      supported_color_modes:
      - brightness
      - color_temp
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      friendly_name: Basement light 1
      supported_features: 32
      state: 'off'
    light.basement_light_2:
      min_color_temp_kelvin: 2700
      max_color_temp_kelvin: 5000
      min_mireds: 200
      max_mireds: 370
      supported_color_modes:
      - brightness
      - color_temp
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      friendly_name: Basement light 2
      supported_features: 32
      state: 'off'
    switch.bedroom:
      friendly_name: Bedroom
      state: 'off'
    switch.kitchen_1:
      friendly_name: Kitchen 1
      state: 'off'
    light.living_1:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 9000
      min_mireds: 111
      max_mireds: 400
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      friendly_name: Living 1
      supported_features: 32
      state: 'off'
    light.living_2:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 9000
      min_mireds: 111
      max_mireds: 400
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      friendly_name: Living 2
      supported_features: 32
      state: 'off'
    light.office_1:
      min_color_temp_kelvin: 2700
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 370
      supported_color_modes:
      - brightness
      - color_temp
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      friendly_name: office 1
      supported_features: 32
      state: 'off'
    light.office_2:
      min_color_temp_kelvin: 2700
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 370
      supported_color_modes:
      - brightness
      - color_temp
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      friendly_name: office 2
      supported_features: 32
      state: 'off'
    light.office_backlight:
      min_color_temp_kelvin: 2700
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 370
      supported_color_modes:
      - brightness
      - color_temp
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      friendly_name: Office Backlight
      supported_features: 32
      state: 'off'
    media_player.tv:
      friendly_name: TV
      supported_features: 152461
      state: 'off'
  metadata: {}
- id: '1704864744838'
  name: living room concentrate
  entities:
    light.living_1:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 9000
      min_mireds: 111
      max_mireds: 400
      supported_color_modes:
      - color_temp
      - hs
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 5847
      color_temp: 171
      hs_color:
      - 29.496
      - 8.81
      rgb_color:
      - 255
      - 243
      - 232
      xy_color:
      - 0.344
      - 0.339
      friendly_name: Living 1
      supported_features: 32
      state: 'on'
    light.living_2:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 9000
      min_mireds: 111
      max_mireds: 400
      supported_color_modes:
      - color_temp
      - hs
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 5714
      color_temp: 175
      hs_color:
      - 28.745
      - 10.321
      rgb_color:
      - 255
      - 241
      - 228
      xy_color:
      - 0.348
      - 0.341
      friendly_name: Living 2
      supported_features: 32
      state: 'on'
    switch.circadian_lighting_whole_house_circadian_switch:
      hs_color:
      brightness:
      colortemp: 2500
      icon: mdi:theme-light-dark
      friendly_name: Whole House Circadian Switch
      state: 'off'
  metadata:
    switch.circadian_lighting_whole_house_circadian_switch:
      entity_only: true
- id: '1714093232734'
  name: TV mode
  entities:
    light.living_1:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 9000
      min_mireds: 111
      max_mireds: 400
      supported_color_modes:
      - color_temp
      - hs
      color_mode: hs
      brightness: 41
      color_temp_kelvin:
      color_temp:
      hs_color:
      - 0
      - 100
      rgb_color:
      - 255
      - 0
      - 0
      xy_color:
      - 0.701
      - 0.299
      friendly_name: Living 1
      supported_features: 32
      state: 'on'
    switch.kitchen_1:
      friendly_name: Kitchen 1
      state: 'off'
    light.office_1:
      min_color_temp_kelvin: 2700
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 370
      supported_color_modes:
      - color_temp
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      friendly_name: office 1
      supported_features: 32
      state: 'off'
    light.office_2:
      min_color_temp_kelvin: 2700
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 370
      supported_color_modes:
      - color_temp
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      friendly_name: office 2
      supported_features: 32
      state: 'off'
    light.office_backlight:
      min_color_temp_kelvin: 2700
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 370
      supported_color_modes:
      - color_temp
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      friendly_name: Office Backlight
      supported_features: 32
      state: 'off'
    switch.bedroom:
      friendly_name: Bedroom
      state: 'off'
    cover.all_shades:
      current_position: 0
      entity_id:
      - cover.bedroom_shades
      - cover.living_room_shades
      friendly_name: All Shades
      supported_features: 15
      state: closed
    light.living_2:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 9000
      min_mireds: 111
      max_mireds: 400
      supported_color_modes:
      - color_temp
      - hs
      color_mode: color_temp
      brightness: 8
      color_temp_kelvin: 2500
      color_temp: 400
      hs_color:
      - 28.874
      - 72.522
      rgb_color:
      - 255
      - 159
      - 70
      xy_color:
      - 0.546
      - 0.389
      friendly_name: Living 2
      supported_features: 32
      state: 'on'
  metadata:
    cover.all_shades:
      entity_only: true
- id: '1717551891701'
  name: Evening Shades
  entities:
    cover.living_room_short_shades:
      current_position: 0
      entity_id:
      - cover.living_room_living_room_short_se
      - cover.living_room_living_room_short_sw
      friendly_name: Living Room Short Shades
      supported_features: 15
      state: closed
    cover.living_room_long_shades:
      current_position: 9
      entity_id:
      - cover.living_room_living_room_big_sw
      - cover.living_room_living_room_big_se
      friendly_name: Living Room Long Shades
      supported_features: 15
      state: open
    cover.bedroom_shades:
      current_position: 15
      entity_id:
      - cover.my_bedroom_bedroom_shade_east
      - cover.my_bedroom_bedroom_shade_north
      friendly_name: Bedroom Shades
      supported_features: 15
      state: open
  icon: mdi:roller-shade
  metadata:
    cover.living_room_short_shades:
      entity_only: true
    cover.living_room_long_shades:
      entity_only: true
    cover.bedroom_shades:
      entity_only: true
- id: '1724202079414'
  name: Computer game night
  entities:
    switch.circadian_lighting_whole_house_circadian_switch:
      hs_color:
      brightness:
      colortemp: 2500
      icon: mdi:theme-light-dark
      friendly_name: Whole House Circadian Switch
      state: 'off'
    light.living_1:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 9000
      min_mireds: 111
      max_mireds: 400
      supported_color_modes:
      - color_temp
      - hs
      color_mode: color_temp
      brightness: 13
      color_temp_kelvin: 2700
      color_temp: 370
      hs_color:
      - 28.395
      - 65.723
      rgb_color:
      - 255
      - 166
      - 87
      xy_color:
      - 0.526
      - 0.387
      friendly_name: Living 1
      supported_features: 32
      state: 'on'
    light.living_2:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 9000
      min_mireds: 111
      max_mireds: 400
      supported_color_modes:
      - color_temp
      - hs
      color_mode: color_temp
      brightness: 13
      color_temp_kelvin: 2700
      color_temp: 370
      hs_color:
      - 28.395
      - 65.723
      rgb_color:
      - 255
      - 166
      - 87
      xy_color:
      - 0.526
      - 0.387
      friendly_name: Living 2
      supported_features: 32
      state: 'on'
    light.office_1:
      min_color_temp_kelvin: 2700
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 370
      supported_color_modes:
      - color_temp
      color_mode: color_temp
      brightness: 26
      color_temp_kelvin: 6500
      color_temp: 153
      hs_color:
      - 49.231
      - 1.944
      rgb_color:
      - 255
      - 254
      - 250
      xy_color:
      - 0.326
      - 0.333
      friendly_name: office 1
      supported_features: 32
      state: 'on'
    light.office_2:
      min_color_temp_kelvin: 2700
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 370
      supported_color_modes:
      - color_temp
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      friendly_name: office 2
      supported_features: 32
      state: 'off'
    light.office_backlight:
      min_color_temp_kelvin: 2700
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 370
      supported_color_modes:
      - color_temp
      color_mode: color_temp
      brightness: 26
      color_temp_kelvin: 6500
      color_temp: 153
      hs_color:
      - 49.231
      - 1.944
      rgb_color:
      - 255
      - 254
      - 250
      xy_color:
      - 0.326
      - 0.333
      friendly_name: Office Backlight
      supported_features: 32
      state: 'on'
  icon: mdi:nintendo-game-boy
  metadata:
    switch.circadian_lighting_whole_house_circadian_switch:
      entity_only: true
    light.living_1:
      entity_only: true
    light.living_2:
      entity_only: true
    light.office_1:
      entity_only: true
    light.office_2:
      entity_only: true
    light.office_backlight:
      entity_only: true
- id: '1724202307062'
  name: Normal lighting
  entities:
    switch.circadian_lighting_whole_house_circadian_switch:
      hs_color:
      - 28.681
      - 71.373
      brightness: 40.8515284684221
      colortemp: 2500
      icon: mdi:theme-light-dark
      friendly_name: Whole House Circadian Switch
      state: 'on'
  metadata:
    switch.circadian_lighting_whole_house_circadian_switch:
      entity_only: true
- id: '1729894733977'
  name: Changing mode
  entities:
    cover.my_bedroom_bedroom_shade_east:
      current_position: 0
      device_id: '2'
      zone_id: '1'
      device_class: shade
      friendly_name: My Bedroom Bedroom Shade East
      supported_features: 15
      state: closed
    cover.my_bedroom_bedroom_shade_north:
      current_position: 0
      device_id: '3'
      zone_id: '2'
      device_class: shade
      friendly_name: My Bedroom Bedroom Shade North
      supported_features: 15
      state: closed
    switch.bedroom:
      friendly_name: Bedroom
      state: 'on'
  metadata: {}
