alias: Arming alarm and leaving
description: ""
triggers:
  - trigger: conversation
    command:
      - I'm Leaving
      - I am leaving
conditions: []
actions:
  - set_conversation_response: ""
  - data: {}
    action: script.leaving_home
mode: single
