alias: Arming alarm and leaving
description: ""
triggers:
  - device_id: 12991409e93a14125e39db65a3b740dc
    domain: alarm_control_panel
    entity_id: ed8fc83278462fc5ba4f6de76da799ad
    type: arming
    for:
      hours: 0
      minutes: 0
      seconds: 10
    trigger: device
  - trigger: conversation
    command: I'm Leaving
conditions: []
actions:
  - set_conversation_response: ""
  - data: {}
    action: script.leaving_home
mode: single
