alias: Arming alarm and leaving
description: ""
trigger:
  - platform: device
    device_id: 12991409e93a14125e39db65a3b740dc
    domain: alarm_control_panel
    entity_id: ed8fc83278462fc5ba4f6de76da799ad
    type: arming
    for:
      hours: 0
      minutes: 0
      seconds: 10
condition: []
action:
  - service: script.leaving_home
    data: {}
mode: single
