alias: "Arrive home routine "
description: ""
trigger:
  - platform: zone
    entity_id: person.hofmadresu
    zone: zone.home
    event: enter
  - type: connected
    platform: device
    device_id: b2482cd7e929c9aa71f6108b82362aa3
    entity_id: acaed035412bb4c8d648fb3d7bc72a5e
    domain: binary_sensor
    enabled: false
condition:
  - condition: device
    device_id: 12991409e93a14125e39db65a3b740dc
    domain: alarm_control_panel
    entity_id: ed8fc83278462fc5ba4f6de76da799ad
    type: is_armed_away
action:
  - metadata: {}
    data:
      message: The house is prepped for you
      title: Welcome home
    action: notify.mobile_app_pixel_8
  - device_id: 12991409e93a14125e39db65a3b740dc
    domain: alarm_control_panel
    entity_id: ed8fc83278462fc5ba4f6de76da799ad
    type: disarm
    code: ""
  - action: script.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: script.unlock_doors
  - alias: Lights on if dark
    if:
      - condition: sun
        after: sunset
        before: sunrise
    then:
      - type: turn_on
        device_id: 0f1815f6576728547da6fbc3a3b69277
        entity_id: d7144b619bd94371cb9c1e6459036229
        domain: switch
      - type: turn_on
        device_id: 8576e7dab40455676993ad9a4bcc5c49
        entity_id: f2899e19720f9c1b0f0c164f3eea4069
        domain: switch
      - type: turn_on
        device_id: 3760e1833184baf271de63cb70927def
        entity_id: 2142caaf7a8101bbb6902e44d162f416
        domain: light
      - type: turn_on
        device_id: c7fbc0c3b546ce9fac5df8edcdc3731f
        entity_id: b5d123c0b7fd2748264a524c8082d027
        domain: light
      - delay:
          hours: 0
          minutes: 10
          seconds: 0
          milliseconds: 0
      - type: turn_off
        device_id: 0f1815f6576728547da6fbc3a3b69277
        entity_id: d7144b619bd94371cb9c1e6459036229
        domain: switch
    else:
      - if:
          - condition: numeric_state
            entity_id: sensor.karb_temperature
            above: 10
        then:
          - metadata: {}
            data: {}
            action: script.zarathustra
            enabled: false
  - if:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "on"
    then:
      - action: input_boolean.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.vacation_mode
mode: single
