alias: "Arrive home routine "
description: ""
triggers:
  - entity_id: person.hofmadresu
    zone: zone.home
    event: enter
    trigger: zone
conditions:
  - condition: device
    device_id: 12991409e93a14125e39db65a3b740dc
    domain: alarm_control_panel
    entity_id: ed8fc83278462fc5ba4f6de76da799ad
    type: is_armed_away
actions:
  - if:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "on"
    then:
      - action: input_boolean.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.vacation_mode
    alias: Turn off vacation mode
  - device_id: 12991409e93a14125e39db65a3b740dc
    domain: alarm_control_panel
    entity_id: ed8fc83278462fc5ba4f6de76da799ad
    type: disarm
    code: "{{!secret alarm_code}}"
  - action: script.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: script.unlock_doors
  - alias: Lights on if dark
    if:
      - condition: sun
        after: sunset
        before: sunrise
    then:
      - type: turn_on
        device_id: 0f1815f6576728547da6fbc3a3b69277
        entity_id: d7144b619bd94371cb9c1e6459036229
        domain: switch
      - type: turn_on
        device_id: 8576e7dab40455676993ad9a4bcc5c49
        entity_id: f2899e19720f9c1b0f0c164f3eea4069
        domain: switch
      - type: turn_on
        device_id: 7a00544c97f80dfcc3ba0fab5f0f2b06
        entity_id: 6aad29377c9d331661aefb7d3aa9bf6c
        domain: light
      - type: turn_on
        device_id: 0eec206f3ae8307023fe6e831b9dc8c2
        entity_id: 4f504f129d920af05dbfed66e23bcf8f
        domain: light
      - delay:
          hours: 0
          minutes: 10
          seconds: 0
          milliseconds: 0
      - type: turn_off
        device_id: 0f1815f6576728547da6fbc3a3b69277
        entity_id: d7144b619bd94371cb9c1e6459036229
        domain: switch
    else:
      - if:
          - condition: numeric_state
            entity_id: sensor.openweathermap_temperature
            above: 10
        then:
          - variables:
              action_open_blinds: "{{ 'OPEN_BLINDS_' ~ context.id }}"
          - alias: Ask to open the blinds
            action: notify.mobile_app_pixel_8
            data:
              message: Open the blinds?
              data:
                actions:
                  - action: "{{ action_open_blinds }}"
                    title: Do it!
          - alias: Wait for a response
            wait_for_trigger:
              - event_type: mobile_app_notification_action
                event_data:
                  action: "{{ action_open_blinds }}"
                trigger: event
            timeout:
              hours: 0
              minutes: 2
              seconds: 0
              milliseconds: 0
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ wait.trigger.event.data.action == action_open_blinds }}"
                sequence:
                  - data: {}
                    action: script.zarathustra
                    enabled: true
mode: single
