alias: Basement automatic lights
description: ""
mode: single
triggers:
  - entity_id:
      - binary_sensor.basement_motion_sensor_motion
    to: "on"
    trigger: state
conditions:
  - condition: and
    conditions:
      - condition: device
        type: is_off
        device_id: 7ee989242547eb89f3064d90902f0eb7
        entity_id: bb00fcbf210a9d5ff50742987089da85
        domain: light
actions:
  - metadata: {}
    data: {}
    action: light.turn_on
    target:
      entity_id:
        - light.basement_light_1
        - light.basement_light_2
  - wait_for_trigger:
      - entity_id:
          - binary_sensor.basement_motion_sensor_motion
        from: "on"
        for:
          hours: 0
          minutes: 5
          seconds: 0
        trigger: state
  - metadata: {}
    data: {}
    action: light.turn_off
    target:
      entity_id:
        - light.basement_light_1
        - light.basement_light_2
