alias: Bedroom light off on shades opened
description: ""
mode: single
triggers:
  - value_template: "  {{state_attr('cover.bedroom_shades', 'current_position') | int == 100 }}"
    for:
      hours: 0
      minutes: 0
      seconds: 30
    trigger: template
conditions:
  - condition: sun
    before: sunset
actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
        - light.bedroom_light_1
        - light.bedroom_light_2
