alias: Change thermostat on window open/close
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.bedroom_window_open_state
    from: null
    to: null
    for:
      hours: 0
      minutes: 1
      seconds: 0
condition: []
action:
  - if:
      - alias: Bedroom window is open
        condition: state
        entity_id: binary_sensor.bedroom_window_open_state
        state: "on"
        for:
          hours: 0
          minutes: 0
          seconds: 0
    then:
      - service: climate.set_hvac_mode
        metadata: {}
        data:
          hvac_mode: "off"
        target:
          entity_id: climate.family_room
        alias: Turn off thermostat
    else:
      - if:
          - condition: numeric_state
            entity_id: sensor.karb_temperature
            above: 80
        then:
          - service: climate.set_hvac_mode
            metadata: {}
            data:
              hvac_mode: cool
            target:
              entity_id: climate.family_room
            alias: Set thermostat to cool
        else:
          - alias: Set thermostat to heat
            service: climate.set_hvac_mode
            metadata: {}
            data:
              hvac_mode: heat
            target:
              entity_id: climate.family_room
        alias: Turn on thermostat
mode: single
