alias: Change thermostat on window open/close
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.bedroom_window_open_state
    from: null
    to: null
    for:
      hours: 0
      minutes: 1
      seconds: 0
condition: []
action:
  - if:
      - alias: Bedroom window is open
        condition: state
        entity_id: binary_sensor.bedroom_window_open_state
        state: "on"
        for:
          hours: 0
          minutes: 0
          seconds: 0
    then:
      - service: climate.set_hvac_mode
        metadata: {}
        data:
          hvac_mode: "off"
        target:
          entity_id: climate.family_room
        alias: Turn off thermostat
    else:
      - service: script.set_thermostat_mode_based_on_outdoor_temp
        metadata: {}
        data: {}
mode: single
