alias: Change thermostat on window open/close
description: ""
triggers:
  - entity_id:
      - binary_sensor.bedroom_window_open_state
    from: null
    to: null
    for:
      hours: 0
      minutes: 1
      seconds: 0
    trigger: state
conditions: []
actions:
  - if:
      - alias: Bedroom window is open
        condition: state
        entity_id: binary_sensor.bedroom_window_open_state
        state: "on"
        for:
          hours: 0
          minutes: 0
          seconds: 0
    then:
      - action: climate.set_fan_mode
        metadata: {}
        data:
          fan_mode: "off"
        target:
          device_id: 695ac42995783206896bb51e715e03e1
      - metadata: {}
        data:
          hvac_mode: "off"
        target:
          entity_id: climate.family_room
        alias: Turn off thermostat
        action: climate.set_hvac_mode
    else:
      - data: {}
        action: script.set_temp_based_on_mode
mode: single
