alias: Create chores
description: ""
triggers:
  - trigger: time
    at: "05:00:00"
conditions: []
actions:
  - action: todo.remove_completed_items
    metadata: {}
    data: {}
    target:
      entity_id: todo.chores
  - action: todo.get_items
    metadata: {}
    data:
      status: needs_action
    response_variable: chores
    target:
      entity_id: todo.chores
  - if:
      - condition: template
        value_template: "{{ now().day < 8 and now().weekday() == 5 }}"
    then:
      - action: script.add_unique_chore
        metadata: {}
        data:
          chore: Clean basement bathroom
    alias: "Add chore: basement bathroom cleaning"
  - if:
      - condition: template
        value_template: "{{ now().day == 3 and now().month == 1 }}"
    then:
      - action: script.add_unique_chore
        metadata: {}
        data:
          chore: Refill emergency water
    alias: "Add chore: refill emergency water"
  - alias: "Add chore: water and feed plant"
    if:
      - condition: template
        value_template: "{{ now().day == 1 }}"
    then:
      - action: script.add_unique_chore
        metadata: {}
        data:
          chore: Water and feed plant
  - alias: "Add chore: set up next month's meals on wheels"
    if:
      - condition: template
        value_template: "{{ now().day == 1 }}"
    then:
      - action: script.add_unique_chore
        metadata: {}
        data:
          chore: Set up next month's meals on wheels
  - alias: "Add chore: clean washer"
    if:
      - condition: numeric_state
        entity_id: sensor.washer_tub_clean_counter
        above: 29
    then:
      - action: script.add_unique_chore
        metadata: {}
        data:
          chore: Clean washer
mode: single
