alias: Create chores
description: ""
triggers:
  - trigger: time
    at: "05:00:00"
conditions: []
actions:
  - alias: Get completed chores
    action: todo.get_items
    metadata: {}
    data:
      status:
        - completed
    response_variable: completedChores
    target:
      entity_id: todo.chores
  - if:
      - condition: template
        value_template: |-
          {{
              completedChores['todo.chores']['items']|selectattr('summary','search','Replace furnace filter')|list|count
              > 0}}
    then:
      - alias: "Add chore: Clean used furnace filter"
        action: script.add_unique_chore
        metadata: {}
        data:
          chore: Clean used furnace filter
    alias: Clean filter if replacement complete
  - action: todo.remove_completed_items
    metadata: {}
    data: {}
    target:
      entity_id: todo.chores
  - action: todo.get_items
    metadata: {}
    data:
      status: needs_action
    response_variable: chores
    target:
      entity_id: todo.chores
  - if:
      - condition: template
        value_template: "{{ now().day == 3 and now().month == 1 }}"
    then:
      - action: script.add_unique_chore
        metadata: {}
        data:
          chore: Refill emergency water
    alias: "Add chore: refill emergency water"
  - alias: Add monthy chores
    if:
      - condition: template
        value_template: "{{ now().day == 1 }}"
    then:
      - action: script.add_unique_chore
        metadata: {}
        data:
          chore: Set up next month's meals on wheels
        alias: "Add chore: Set up next month's meals on wheels"
      - action: script.add_unique_chore
        metadata: {}
        data:
          chore: Water and feed plant
        alias: "Add chore: Water and feed plant"
      - action: script.add_unique_chore
        metadata: {}
        data:
          chore: Clean basement bathroom
        alias: "Add chore: Clean basement bathroom"
      - alias: "Add chore: Pay bills"
        action: script.add_unique_chore
        metadata: {}
        data:
          chore: Pay bills
  - alias: "Add chore: clean washer"
    if:
      - condition: numeric_state
        entity_id: sensor.washer_tub_clean_counter
        above: 29
    then:
      - action: script.add_unique_chore
        metadata: {}
        data:
          chore: Clean washer
  - alias: "Add chore: Replace furnace filter"
    if:
      - condition: template
        value_template: "{{ now().day == 1 and now().month % 3 == 1}}"
    then:
      - alias: "Add chore: Replace furnace filter"
        action: script.add_unique_chore
        metadata: {}
        data:
          chore: Replace furnace filter
  - if:
      - condition: and
        conditions:
          - condition: time
            weekday:
              - mon
              - thu
              - sat
          - condition: state
            entity_id: input_boolean.hummingbird_feeder_out
            state: "on"
    then:
      - alias: "Add chore: Refresh hummingbird liquid"
        action: script.add_unique_chore
        metadata: {}
        data:
          chore: Refresh hummingbird liquid
    alias: "Add chore: Refresh hummingbird liquid"
mode: single
