alias: Entryway on for motion
description: ""
trigger:
  - type: motion
    platform: device
    device_id: f1a451d00e600cabf0bc652eeb472934
    entity_id: 7d28ef5d2c38a911fdaed396414d3e47
    domain: binary_sensor
condition:
  - condition: and
    conditions:
      - condition: sun
        after: sunset
        before: sunrise
      - condition: device
        type: is_off
        device_id: 5bb08e144b56c7704e730b5423bbd866
        entity_id: e61c2892bd3b7db050d5212b10ed5230
        domain: light
action:
  - type: turn_on
    device_id: 5bb08e144b56c7704e730b5423bbd866
    entity_id: e61c2892bd3b7db050d5212b10ed5230
    domain: light
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 5bb08e144b56c7704e730b5423bbd866
    entity_id: e61c2892bd3b7db050d5212b10ed5230
    domain: light
mode: single
