alias: Entryway on for motion
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.camera1_person
    to:
      - "on"
conditions:
  - condition: and
    conditions:
      - condition: sun
        after: sunset
        before: sunrise
      - condition: device
        type: is_off
        device_id: 5bb08e144b56c7704e730b5423bbd866
        entity_id: e61c2892bd3b7db050d5212b10ed5230
        domain: light
actions:
  - type: turn_on
    device_id: 5bb08e144b56c7704e730b5423bbd866
    entity_id: e61c2892bd3b7db050d5212b10ed5230
    domain: light
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 5bb08e144b56c7704e730b5423bbd866
    entity_id: e61c2892bd3b7db050d5212b10ed5230
    domain: light
mode: single
