alias: Furnace light off when door closes
description: ""
triggers:
  - type: not_opened
    device_id: a510705bfe79b9d03cd8abdd0691261d
    entity_id: efa64b8a628e01a0ff02695b11d75ec7
    domain: binary_sensor
    trigger: device
conditions: []
actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      device_id: 4256697c800769ec15aad2c3b486ecbe
mode: single
