alias: Holiday lights night
description: ""
trigger:
  - platform: sun
    event: sunset
    offset: "-01:00:00"
condition: []
action:
  - action: script.run_holiday_lights
    metadata: {}
    data: {}
  - wait_for_trigger:
      - platform: time
        at: "23:59:59"
  - metadata: {}
    data: {}
    target:
      device_id: 957afb69a90840abaf62c497bf3c4185
    action: light.turn_off
mode: single
