alias: Holiday lights
description: ""
trigger:
  - platform: sun
    event: sunset
    offset: "-01:00:00"
condition: []
action:
  - alias: turn on murica if US-type holiday
    if:
      - condition: or
        conditions:
          - condition: state
            entity_id: sensor.today_s_holiday
            state: Independence Day
          - condition: state
            entity_id: sensor.today_s_holiday
            state: Memorial Day
          - condition: state
            entity_id: sensor.today_s_holiday
            state: Labor Day
          - condition: state
            entity_id: sensor.today_s_holiday
            state: Veterans Day
    then:
      - metadata: {}
        data:
          effect: murica
        target:
          device_id: 957afb69a90840abaf62c497bf3c4185
        action: light.turn_on
  - alias: Juneteenth
    if:
      - condition: state
        entity_id: sensor.today_s_holiday
        state: Juneteenth National Independence Day
    then:
      - metadata: {}
        data:
          effect: Juneteenth
        target:
          device_id: 957afb69a90840abaf62c497bf3c4185
        action: light.turn_on
  - alias: Christmas
    if:
      - condition: template
        value_template: "{{ now().month == 12 and now().day != 12 }}"
    then:
      - alias: Christmas on 0/3
        if:
          - condition: template
            value_template: "{{ now().day % 3 == 0 }}"
        then:
          - metadata: {}
            data:
              effect: Christmas
            target:
              device_id: 957afb69a90840abaf62c497bf3c4185
            action: light.turn_on
      - alias: Christmas Gift on 1/3
        if:
          - condition: template
            value_template: "{{ now().day % 3 == 1 }}"
        then:
          - metadata: {}
            data:
              effect: Christmas Gift
            target:
              device_id: 957afb69a90840abaf62c497bf3c4185
            action: light.turn_on
      - alias: Christmas Tree on 2/3
        if:
          - condition: template
            value_template: "{{ now().day % 3 == 2 }}"
        then:
          - metadata: {}
            data:
              effect: Christmas Tree
            target:
              device_id: 957afb69a90840abaf62c497bf3c4185
            action: light.turn_on
  - alias: Birthday
    if:
      - condition: state
        entity_id: binary_sensor.today_has_birthdays
        state: "on"
    then:
      - metadata: {}
        data:
          effect: Birthday
        target:
          device_id: 957afb69a90840abaf62c497bf3c4185
        action: light.turn_on
  - alias: Party
    if:
      - condition: or
        conditions:
          - condition: state
            entity_id: sensor.today_s_events
            state: Beerfest
    then:
      - metadata: {}
        data:
          effect: Party
        target:
          device_id: 957afb69a90840abaf62c497bf3c4185
        action: light.turn_on
  - if:
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ now().month == 10 and now().day == 31 }}"
          - condition: state
            entity_id: binary_sensor.hofmadresu_pixel_8_wireless_connected
            state: "on"
    then:
      - metadata: {}
        data:
          effect: My Halloween
        target:
          device_id: 957afb69a90840abaf62c497bf3c4185
        action: light.turn_on
    alias: Halloween
  - wait_for_trigger:
      - platform: time
        at: "23:59:59"
  - metadata: {}
    data: {}
    target:
      device_id: 957afb69a90840abaf62c497bf3c4185
    action: light.turn_off
mode: single
