alias: House temp
description: ""
trigger:
  - platform: time_pattern
    hours: /1
  - platform: state
    entity_id:
      - input_boolean.sick_mode
      - input_boolean.pet_mode
condition:
  - alias: Not off nor eco
    condition: not
    conditions:
      - condition: or
        conditions:
          - condition: device
            device_id: 695ac42995783206896bb51e715e03e1
            domain: climate
            entity_id: c6c45aeb39a40b31cfc9e0bd944c67ae
            type: is_hvac_mode
            hvac_mode: "off"
          - condition: device
            device_id: 695ac42995783206896bb51e715e03e1
            domain: climate
            entity_id: c6c45aeb39a40b31cfc9e0bd944c67ae
            type: is_preset_mode
            preset_mode: eco
action:
  - service: script.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: script.set_temp_based_on_mode
mode: single
