alias: Illuminate
description: ""
triggers:
  - trigger: conversation
    command: Illuminate
conditions: []
actions:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      area_id:
        - living_room
        - office
        - bedroom
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      device_id:
        - 8576e7dab40455676993ad9a4bcc5c49
mode: single
