alias: Keep air good
description: ""
trigger:
  - type: carbon_dioxide
    platform: device
    device_id: d276e61bffda959e361f8b8683b8afd6
    entity_id: 070616c02a3b9688b3a97f4023c0b515
    domain: sensor
    above: 700
condition:
  - condition: and
    conditions:
      - condition: not
        conditions:
          - condition: device
            device_id: 23709abe8dedaad622d3af350cc22555
            domain: climate
            entity_id: 2e2068e09ae328d4105e9a1a7f6d148c
            type: is_hvac_mode
            hvac_mode: "off"
        alias: Nest not off
      - condition: or
        conditions:
          - type: is_connected
            condition: device
            device_id: 73cf62095f63eb5a9abc0ef8d0494a64
            entity_id: 25fca37d1879ff89c99e5dace6790ba9
            domain: binary_sensor
          - condition: device
            device_id: 6dbdf144428b850689a68b1c6b7b19de
            domain: device_tracker
            entity_id: d366159c7cf8e5ec7b73b94ca8db9a81
            type: is_home
action:
  - service: climate.set_fan_mode
    target:
      device_id: 23709abe8dedaad622d3af350cc22555
    data:
      fan_mode: "on"
  - wait_for_trigger:
      - type: carbon_dioxide
        platform: device
        device_id: d276e61bffda959e361f8b8683b8afd6
        entity_id: 070616c02a3b9688b3a97f4023c0b515
        domain: sensor
        below: 600
    alias: Wait for good air
  - service: climate.set_fan_mode
    target:
      device_id: 23709abe8dedaad622d3af350cc22555
    data:
      fan_mode: "off"
mode: single
