alias: Keep air good
description: ""
trigger:
  - type: carbon_dioxide
    platform: device
    device_id: d276e61bffda959e361f8b8683b8afd6
    entity_id: 070616c02a3b9688b3a97f4023c0b515
    domain: sensor
    above: 700
condition:
  - condition: and
    conditions:
      - alias: Nest not off
        condition: not
        conditions:
          - condition: device
            device_id: 695ac42995783206896bb51e715e03e1
            domain: climate
            entity_id: c6c45aeb39a40b31cfc9e0bd944c67ae
            type: is_hvac_mode
            hvac_mode: "off"
      - condition: zone
        entity_id: person.hofmadresu
        zone: zone.home
action:
  - service: climate.set_fan_mode
    data:
      fan_mode: "on"
    target:
      device_id: 695ac42995783206896bb51e715e03e1
  - wait_for_trigger:
      - type: carbon_dioxide
        platform: device
        device_id: d276e61bffda959e361f8b8683b8afd6
        entity_id: 070616c02a3b9688b3a97f4023c0b515
        domain: sensor
        below: 600
    alias: Wait for good air
  - service: climate.set_fan_mode
    data:
      fan_mode: "off"
    target:
      device_id: 695ac42995783206896bb51e715e03e1
mode: restart
