alias: Living room dusk
description: ""
trigger:
  - platform: sun
    event: sunset
    offset: "-1:00:00"
condition:
  - condition: and
    conditions:
      - condition: zone
        entity_id: person.hofmadresu
        zone: zone.home
action:
  - type: turn_on
    device_id: 3760e1833184baf271de63cb70927def
    entity_id: 2142caaf7a8101bbb6902e44d162f416
    domain: light
  - type: turn_on
    device_id: c7fbc0c3b546ce9fac5df8edcdc3731f
    entity_id: b5d123c0b7fd2748264a524c8082d027
    domain: light
mode: single
