alias: Living room dusk
description: ""
triggers:
  - event: sunset
    offset: "-1:00:00"
    trigger: sun
conditions:
  - condition: and
    conditions:
      - condition: zone
        entity_id: person.hofmadresu
        zone: zone.home
actions:
  - type: turn_on
    device_id: 7a00544c97f80dfcc3ba0fab5f0f2b06
    entity_id: 6aad29377c9d331661aefb7d3aa9bf6c
    domain: light
  - type: turn_on
    device_id: 0eec206f3ae8307023fe6e831b9dc8c2
    entity_id: 4f504f129d920af05dbfed66e23bcf8f
    domain: light
mode: single
