alias: Living room lights off on shades opened
description: ""
mode: single
triggers:
  - value_template: "  {{state_attr('cover.living_room_short_shades', 'current_position') | int == 100 }}"
    for:
      hours: 0
      minutes: 0
      seconds: 30
    trigger: template
  - value_template: "  {{state_attr('cover.living_room_long_shades', 'current_position') | int == 100 }}"
    for:
      hours: 0
      minutes: 0
      seconds: 30
    trigger: template
conditions:
  - condition: sun
    before: sunset
actions:
  - type: turn_off
    device_id: 0eec206f3ae8307023fe6e831b9dc8c2
    entity_id: 4f504f129d920af05dbfed66e23bcf8f
    domain: light
  - type: turn_off
    device_id: 7a00544c97f80dfcc3ba0fab5f0f2b06
    entity_id: 6aad29377c9d331661aefb7d3aa9bf6c
    domain: light
