alias: Make Me Move
description: ""
triggers:
  - minutes: "30"
    trigger: time_pattern
  - minutes: "0"
    trigger: time_pattern
conditions:
  - condition: time
    after: "09:00:00"
    before: "17:00:00"
    weekday:
      - fri
      - thu
      - wed
      - tue
      - mon
  - condition: or
    conditions:
      - condition: zone
        entity_id: person.hofmadresu
        zone: zone.home
      - condition: zone
        entity_id: person.hofmadresu
        zone: zone.aunties
      - condition: zone
        entity_id: person.hofmadresu
        zone: zone.parents
  - condition: state
    entity_id: input_boolean.sick_mode
    state: "off"
actions:
  - variables:
      anywhereExercises:
        - name: Pushups
          unit: reps
          count: "10"
        - name: Situps
          unit: reps
          count: "10"
        - name: Squats
          unit: reps
          count: "10"
        - name: Planks
          unit: seconds
          count: "30"
        - name: Lunges
          unit: reps
          count: "5"
      nonOfficeExercises:
        - name: Wall Sits
          unit: seconds
          count: "30"
        - name: Vault Ups
          unit: reps
          count: "10"
        - name: Leg Lifts
          unit: reps
          count: "10"
        - name: Superman Pushups
          unit: reps
          count: "5"
      homeEquipmentExercises:
        - name: Kettlebell Swings
          unit: reps
          count: "10"
        - name: Kettlebell Halos
          unit: reps
          count: "2"
        - name: Turkish Get Ups
          unit: reps
          count: "2"
        - name: Pullups
          unit: reps
          count: "10"
        - name: Curls
          unit: reps
          count: "10"
        - name: Stair Climbs
          unit: reps
          count: "16"
        - name: Triceps Lifts
          unit: reps
          count: "10"
        - name: Swimmer's Presses
          unit: reps
          count: "5"
        - name: One Footed Swimmer's Presses
          unit: reps
          count: "2"
        - name: Rope Jumps
          unit: reps
          count: 20
      isHome: "{{'person.hofmadresu' in state_attr('zone.home', 'persons')}}"
      isAtAunties: "{{'person.hofmadresu' in state_attr('zone.aunties', 'persons')}}"
      isAtParents: "{{'person.hofmadresu' in state_attr('zone.parents', 'persons')}}"
      availableNonOfficeExercises: "{{nonOfficeExercises if isHome or isAtAunties or isAtParents else []}}"
      availableHomeEquipmentExercises: "{{homeEquipmentExercises if isHome else []}}"
      exercises: >-
        {{anywhereExercises + availableNonOfficeExercises +
        availableHomeEquipmentExercises}}
      activeExercises: "{{exercises}}"
      randMax: "{{activeExercises|length}}"
      exerciseIndex: "{{range(0, randMax)|random}}"
      repsMessage: >-
        Do {{activeExercises[exerciseIndex].count}}
        {{activeExercises[exerciseIndex].name}}
      secondsMessage: >-
        Do {{activeExercises[exerciseIndex].name}} for
        {{activeExercises[exerciseIndex].count}} seconds
      message: >-
        {{repsMessage if activeExercises[exerciseIndex].unit == 'reps' else
        secondsMessage}}
  - data:
      title: Time To Move
      message: "{{message}}"
      data:
        channel: Make Me Move Priority
        priority: high
        ttl: 0
        notification_icon: mdi:weight-lifter
        icon_url: >-
          https://raw.githubusercontent.com/HofmaDresu/HomeAssistant/main/icons/MakeMeMoveIcon.png
        timeout: "{{30 * 60}}"
    action: notify.mobile_app_pixel_8
mode: single
