alias: Monthly full backup
description: ""
trigger:
  - platform: time
    at: "03:00:00"
condition:
  - condition: template
    value_template: "{{ now().day == 1 }}"
    alias: Is first of month
action:
  - service: hassio.backup_full
    metadata: {}
    data:
      compressed: true
      homeassistant_exclude_database: false
mode: single
