alias: Notify to open windows
description: ""
triggers:
  - entity_id:
      - sensor.openweathermap_temperature
    above: 60
    below: 80
    trigger: numeric_state
conditions:
  - condition: state
    entity_id: person.hofmadresu
    state: home
  - condition: time
    after: "07:00:00"
    before: "22:00:00"
  - condition: state
    entity_id: binary_sensor.bedroom_window_open_state
    state: "off"
  - condition: numeric_state
    entity_id: sensor.ypsilanti_michigan_usa_air_quality_index
    below: 100
  - condition: state
    entity_id: sensor.openweathermap_precipitation_kind
    state: None
    for:
      hours: 1
      minutes: 0
      seconds: 0
actions:
  - metadata: {}
    data:
      message: Temp good to open windows
      title: Open Windows
    action: notify.mobile_app_pixel_8
mode: single
