alias: Notify to open windows
description: ""
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.karb_temperature
    above: 60
    below: 80
condition:
  - condition: state
    entity_id: person.hofmadresu
    state: home
  - condition: time
    after: "07:00:00"
    before: "22:00:00"
  - condition: state
    entity_id: binary_sensor.bedroom_window_open_state
    state: "off"
action:
  - service: notify.mobile_app_pixel_8
    metadata: {}
    data:
      message: Temp good to open windows
      title: Open Windows
mode: single
