alias: Office automatic lights
description: ""
triggers:
  - entity_id:
      - binary_sensor.office_motion_sensor_motion
    to: "on"
    trigger: state
conditions:
  - condition: device
    type: is_off
    device_id: bad671e7062197c2244063c9ab807b41
    entity_id: 570122fb667e2bbf465c4b1eee4cc5b8
    domain: light
  - condition: device
    type: is_off
    device_id: 1155e017f2b58ecdf76d69807001a0b9
    entity_id: 525207ce60b068d636526e83f993b12a
    domain: light
  - condition: state
    entity_id: input_boolean.pet_mode
    state: "off"
  - condition: numeric_state
    entity_id: cover.office_shades
    attribute: current_position
    below: 50
actions:
  - metadata: {}
    data: {}
    target:
      area_id: office
    action: light.turn_on
  - wait_for_trigger:
      - entity_id:
          - binary_sensor.office_motion_sensor_motion
        from: "on"
        for:
          hours: 0
          minutes: 1
          seconds: 0
        trigger: state
  - metadata: {}
    data: {}
    target:
      area_id: office
    action: light.turn_off
mode: single
