description: ""
mode: single
triggers:
  - value_template: "  {{state_attr('cover.office_shades', 'current_position') | int == 100 }}"
    for:
      hours: 0
      minutes: 0
      seconds: 30
    trigger: template
conditions:
  - condition: sun
    before: sunset
actions:
  - type: turn_off
    device_id: bad671e7062197c2244063c9ab807b41
    entity_id: 570122fb667e2bbf465c4b1eee4cc5b8
    domain: light
  - type: turn_off
    device_id: 1155e017f2b58ecdf76d69807001a0b9
    entity_id: 525207ce60b068d636526e83f993b12a
    domain: light
  - type: turn_off
    device_id: 53c67fc630ffb53184d225bbfc7c2fa8
    entity_id: df93ec8a60392af9342a2076858609f2
    domain: light
alias: Office lights off on shade open
