alias: Protect from heat
description: ""
mode: single
triggers:
  - entity_id:
      - sensor.openweathermap_feels_like_temperature
    above: 89
    trigger: numeric_state
  - entity_id:
      - sensor.openweathermap_temperature
    above: 89
    trigger: numeric_state
conditions:
  - condition: and
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: cover.south_shades
            state: open
          - condition: state
            entity_id: binary_sensor.bedroom_window_open_state
            state: "on"
      - condition: state
        entity_id: person.hofmadresu
        state: home
actions:
  - alias: If shades and windows both open
    if:
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.bedroom_window_open_state
            state: "on"
          - condition: state
            entity_id: cover.south_shades
            state: open
    then:
      - metadata: {}
        data:
          cache: false
          entity_id: media_player.home_assistant_voice_091b0c_media_player
          message: >-
            Heat index is very high, you should close windows. South shades will
            close in 5 minutes
        action: tts.cloud_say
      - data:
          title: Extreme high temperature
          message: >-
            Heat index is very high, you should close windows. South shades will
            close in 5 minutes
        action: notify.mobile_app_pixel_8
      - delay:
          hours: 0
          minutes: 5
          seconds: 0
          milliseconds: 0
      - metadata: {}
        data: {}
        target:
          entity_id: cover.south_shades
        action: cover.close_cover
  - alias: If only shades open
    if:
      - condition: and
        conditions:
          - condition: state
            entity_id: cover.south_shades
            state: open
          - condition: not
            conditions:
              - condition: state
                entity_id: binary_sensor.bedroom_window_open_state
                state: "on"
            alias: Windows not open
    then:
      - metadata: {}
        data: {}
        target:
          entity_id: cover.south_shades
        action: cover.close_cover
  - alias: If only windows open
    if:
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.bedroom_window_open_state
            state: "on"
          - alias: Shades not open
            condition: not
            conditions:
              - condition: state
                entity_id: cover.south_shades
                state: open
    then:
      - metadata: {}
        data:
          title: Extreme high temperature
          message: Heat index is very high, you should close windows
        action: notify.persistent_notification
      - metadata: {}
        data:
          cache: false
          entity_id: media_player.home_assistant_voice_091b0c_media_player
          message: Heat index is very high, you should close windows
        action: tts.cloud_say
