alias: Set alarm when plugged in
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.matt_s_phone_pixel_8_battery_state_2
    to: charging
    from: null
condition:
  - condition: and
    conditions:
      - condition: device
        type: is_on
        device_id: d4b4dce9f0f3fcdf3e769a70ff259468
        entity_id: 89d5346579b899623f4d4f45014c604a
        domain: switch
      - condition: not
        conditions:
          - condition: state
            entity_id: input_boolean.alarm_circuitbreaker
            state: "on"
      - condition: or
        conditions:
          - condition: time
            after: "21:00:00"
            weekday:
              - sat
              - fri
              - thu
              - wed
              - tue
              - mon
              - sun
          - condition: time
            before: "04:00:00"
            weekday:
              - sat
              - fri
              - thu
              - wed
              - tue
              - mon
              - sun
      - condition: zone
        entity_id: person.hofmadresu
        zone: zone.home
action:
  - parallel:
      - if:
          - condition: template
            value_template: "{{true}}"
        then:
          - action: script.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: script.lock_doors
          - device_id: 12991409e93a14125e39db65a3b740dc
            domain: alarm_control_panel
            entity_id: ed8fc83278462fc5ba4f6de76da799ad
            type: arm_home
            code: ""
          - delay:
              hours: 0
              minutes: 1
              seconds: 0
              milliseconds: 0
          - target:
              entity_id: scene.power_off
            metadata: {}
            action: scene.turn_on
      - data: {}
        action: script.morning_routine
mode: single
