alias: Set morning alarm override
description: ""
triggers:
  - trigger: conversation
    command:
      - Set morning alarm to {time}
conditions: []
actions:
  - action: input_datetime.set_datetime
    metadata: {}
    data:
      time: "{{trigger.slots.time}}"
    target:
      entity_id: input_datetime.alarm_override_time
  - action: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.alarm_override_active
mode: single
