alias: Terrible air notification
description: ""
trigger:
  - type: carbon_dioxide
    platform: device
    device_id: d276e61bffda959e361f8b8683b8afd6
    entity_id: 070616c02a3b9688b3a97f4023c0b515
    domain: sensor
    above: 1000
  - type: carbon_dioxide
    platform: device
    device_id: d276e61bffda959e361f8b8683b8afd6
    entity_id: 070616c02a3b9688b3a97f4023c0b515
    domain: sensor
    above: 800
    for:
      hours: 1
      minutes: 0
      seconds: 0
condition:
  - condition: zone
    entity_id: person.hofmadresu
    zone: zone.home
action:
  - service: notify.mobile_app_pixel_8
    data:
      title: Terrible air, maybe you should open a window
      message: CO2 is very high
mode: single
