alias: Terrible air notification
description: ""
triggers:
  - type: carbon_dioxide
    device_id: d276e61bffda959e361f8b8683b8afd6
    entity_id: 070616c02a3b9688b3a97f4023c0b515
    domain: sensor
    above: 1000
    trigger: device
    for:
      hours: 0
      minutes: 10
      seconds: 0
  - type: carbon_dioxide
    device_id: d276e61bffda959e361f8b8683b8afd6
    entity_id: 070616c02a3b9688b3a97f4023c0b515
    domain: sensor
    above: 800
    for:
      hours: 1
      minutes: 0
      seconds: 0
    trigger: device
conditions:
  - condition: and
    conditions:
      - condition: zone
        entity_id: person.hofmadresu
        zone: zone.home
      - condition: not
        conditions:
          - condition: state
            entity_id: binary_sensor.bedroom_window_open_state
            state: "on"
    alias: Home and window is not open
actions:
  - data:
      title: Terrible air, maybe you should open a window
      message: CO2 is very high
    action: notify.mobile_app_pixel_8
mode: single
