alias: Vacation mode off
description: ""
trigger:
  - platform: state
    entity_id:
      - input_boolean.vacation_mode
    from: "on"
    to: "off"
condition: []
action:
  - device_id: 695ac42995783206896bb51e715e03e1
    domain: climate
    entity_id: c6c45aeb39a40b31cfc9e0bd944c67ae
    type: set_preset_mode
    preset_mode: none
  - target:
      entity_id:
        - input_boolean.vacation_mode
        - input_boolean.vacuum_circuitbreaker
    data: {}
    action: input_boolean.turn_off
  - target:
      entity_id: script.set_temp_based_on_mode
    data: {}
    action: script.turn_on
  - metadata: {}
    data: {}
    target:
      entity_id: switch.non_essential_outlets
    action: switch.turn_on
mode: single
