alias: Vacation mode off
description: ""
trigger:
  - type: connected
    platform: device
    device_id: 73cf62095f63eb5a9abc0ef8d0494a64
    entity_id: 25fca37d1879ff89c99e5dace6790ba9
    domain: binary_sensor
  - platform: zone
    entity_id: person.hofmadresu
    zone: zone.dtw
    event: enter
  - platform: zone
    entity_id: person.hofmadresu
    zone: zone.jackson
    event: enter
  - platform: zone
    entity_id: person.hofmadresu
    zone: zone.us_23_96
    event: enter
condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: "on"
action:
  - device_id: 695ac42995783206896bb51e715e03e1
    domain: climate
    entity_id: c6c45aeb39a40b31cfc9e0bd944c67ae
    type: set_preset_mode
    preset_mode: none
  - alias: Turn on heat if cold
    if:
      - condition: and
        conditions:
          - condition: device
            device_id: 695ac42995783206896bb51e715e03e1
            domain: climate
            entity_id: c6c45aeb39a40b31cfc9e0bd944c67ae
            type: is_hvac_mode
            hvac_mode: "off"
          - type: is_temperature
            condition: device
            device_id: 695ac42995783206896bb51e715e03e1
            entity_id: fe7d20a775b5d52b1009b9f293aa91dc
            domain: sensor
            below: 60
    then:
      - device_id: 695ac42995783206896bb51e715e03e1
        domain: climate
        entity_id: c6c45aeb39a40b31cfc9e0bd944c67ae
        type: set_hvac_mode
        hvac_mode: heat
  - service: input_boolean.turn_off
    target:
      entity_id:
        - input_boolean.vacation_mode
        - input_boolean.vacuum_circuitbreaker
    data: {}
mode: single
