alias: Vacuum main floor
description: ""
trigger:
  - platform: time
    at: "11:00:00"
condition:
  - condition: state
    entity_id: input_boolean.vacuum_circuitbreaker
    state: "off"
action:
  - if:
      - condition: time
        weekday:
          - sun
    then:
      - service: vacuum.set_fan_speed
        target:
          entity_id: vacuum.roborock_s7_maxv
        data:
          fan_speed: max
      - device_id: 76db24d3a176285f3be6d972ee76b37a
        domain: select
        entity_id: dfbe856fbf9eebc63d793e257ef12970
        type: select_option
        option: moderate
      - service: vacuum.start
        target:
          entity_id: vacuum.roborock_s7_maxv
        data: {}
  - if:
      - condition: time
        weekday:
          - wed
    then:
      - service: vacuum.set_fan_speed
        target:
          entity_id: vacuum.roborock_s7_maxv
        data:
          fan_speed: quiet
      - device_id: 76db24d3a176285f3be6d972ee76b37a
        domain: select
        entity_id: dfbe856fbf9eebc63d793e257ef12970
        type: select_option
        option: mild
      - service: vacuum.start
        target:
          entity_id: vacuum.roborock_s7_maxv
        data: {}
  - if:
      - condition: time
        weekday:
          - fri
    then:
      - service: vacuum.set_fan_speed
        target:
          entity_id: vacuum.roborock_s7_maxv
        data:
          fan_speed: quiet
      - device_id: 76db24d3a176285f3be6d972ee76b37a
        domain: select
        entity_id: dfbe856fbf9eebc63d793e257ef12970
        type: select_option
        option: "off"
      - service: vacuum.start
        target:
          entity_id: vacuum.roborock_s7_maxv
        data: {}
mode: single
