alias: Work run mode ringer volume
description: ""
trigger:
  - platform: time
    at: "23:00:00"
condition:
  - condition: state
    entity_id: calendar.on_call_schedule_for_matt_hoffman
    state: "on"
action:
  - device_id: 6dbdf144428b850689a68b1c6b7b19de
    domain: mobile_app
    type: notify
    message: command_volume_level
    data:
      media_stream: ring_stream
      command: 7
    alias: Set loud volume
  - delay:
      hours: 9
      minutes: 0
      seconds: 0
      milliseconds: 0
  - device_id: 6dbdf144428b850689a68b1c6b7b19de
    domain: mobile_app
    type: notify
    message: command_volume_level
    data:
      media_stream: ring_stream
      command: 3
    alias: Set normal volume
mode: single
