alias: Work run mode ringer volume
description: ""
trigger:
  - platform: time
    at: "23:00:00"
  - platform: time
    at: "07:00:00"
condition:
  - condition: state
    entity_id: input_boolean.work_run_mode
    state: "on"
action:
  - device_id: 6dbdf144428b850689a68b1c6b7b19de
    domain: mobile_app
    type: notify
    message: command_volume_level
    data:
      media_stream: ring_stream
      command: 3
  - if:
      - condition: time
        after: "07:00:00"
        before: "23:00:00"
    then:
      - device_id: 6dbdf144428b850689a68b1c6b7b19de
        domain: mobile_app
        type: notify
        message: command_volume_level
        data:
          media_stream: ring_stream
          command: 3
        alias: Set normal volume
    else:
      - device_id: 6dbdf144428b850689a68b1c6b7b19de
        domain: mobile_app
        type: notify
        message: command_volume_level
        data:
          media_stream: ring_stream
          command: 7
        alias: Set loud volume
mode: single
